## to run
## $ docker-compose up

# question_answering:
#   image: lucida
#   links:
#     - command_center:command_center
#   environment:
#     - DOCKER_QUESTION_ANSWER=8090
#     - DOCKER_COMMAND_CENTER=8080
#   command: bash -c "sleep 10 && ./entry_qa.sh"
#   command: ./entry_qa.sh

# speech_recognition:
#   image: lucida
#   links:
#     - command_center:command_center
#   environment:
#     - DOCKER_SPEECH_RECOGNITION=8091
#     - DOCKER_COMMAND_CENTER=8080
#   command: ./entry_asr.sh

# image_matching:
#   image: lucida
#   links:
#     - command_center:command_center
#   environment:
#     - DOCKER_IMAGE_MATCHING=8092
#     - DOCKER_COMMAND_CENTER=8080
#   command: ./entry_imm.sh
#
# command_center:
#   image: lucida
#   environment:
#     - DOCKER_COMMAND_CENTER=8080
#   ports:
#     - "8080:8080"
#   command: ./entry_cc.sh

all_services:
  image: lucida
  ports:
    - "8080:8080"
  command: bash -c "supervisord"
