## to run
## $ docker-compose up

lucida_services:
  image: claritylab/lucida:tutorial
  ports:
    - "8090:8090"
    - "8081:8081"
  command: bash -c "supervisord"

# lucida_asr:
#   image: claritylab/lucida-asr
#   ports:
#     - "8888:8888"
#   command: bash -c "supervisord"
