## to run
## $ docker-compose up

command_center:
  image: lucida
  links:
    - question_answering:question_answering
    - speech_recognition:speech_recognition
    - image_matching:image_matching
  environment:
    - DOCKER_COMMAND_CENTER=8080
  command: cd lucida/commandcenter && "./cmd_server $DOCKER_COMMAND_CENTER"
  ports:
    - "8080:8080"

question_answering:
  image: lucida
  environment:
    - DOCKER_QUESTION_ANSWER=8090
    - DOCKER_COMMAND_CENTER=8080
  command: cd lucida/questionanswer/lucida && \
    ./start-qa.sh $DOCKER_QUESTION_ANSWER $DOCKER_COMMAND_CENTER

speech_recognition:
  image: lucida
  environment:
    - DOCKER_SPEECH_RECOGNITION=8091
    - DOCKER_COMMAND_CENTER=8080
  command: cd lucida/speechrecognition/lucida && \
    ./asr_server $DOCKER_SPEECH_RECOGNITION $DOCKER_COMMAND_CENTER

image_matching:
  image: lucida
  environment:
    - DOCKER_IMAGE_MATCHING=8092
    - DOCKER_COMMAND_CENTER=8080
  command: cd lucida/imagematching/lucida && \
    ./imm_server $DOCKER_IMAGE_MATCHING $DOCKER_COMMAND_CENTER
